import { randomUUID } from 'node:crypto';
import type { CodexAdapter } from './types.js';
import { mapThreadToProject, type ProjectMapping } from './projectMapping.js';
import type { WssTransport } from './wssTransport.js';
import { normalizeThread } from './threadNormalize.js';
export class CatalogSync {
 constructor(readonly adapter:CodexAdapter,readonly transport:WssTransport,readonly mappings:ProjectMapping[],readonly isAuthorized:(target:{projectId:string;threadId:string})=>boolean=()=>false){}
 async sync(){const snapshotId=`snap-${randomUUID()}`;this.transport.send({protocol:'hc/1',type:'catalog.snapshot.begin',payload:{snapshotId}});let cursor:string|undefined;const unique=new Map<string,{thread:any;project:ProjectMapping}>();do{const page=await this.adapter.listThreads(cursor);for(const thread of page.data){const project=mapThreadToProject(thread.cwd,this.mappings);if(!project)continue;const previous=unique.get(thread.threadId);if(!previous||isNewer(thread.updatedAt,previous.thread.updatedAt))unique.set(thread.threadId,{thread,project});}cursor=page.nextCursor;}while(cursor);const items:any[]=[];for(const {thread,project} of unique.values()){const authorized=this.isAuthorized({projectId:project.projectId,threadId:thread.threadId});const result=authorized?normalizeThread(await this.adapter.readThread(thread.threadId)):undefined;items.push({projectId:project.projectId,projectName:project.name,threadId:thread.threadId,title:thread.title,titleSource:thread.titleSource,status:result?.status??thread.status,updatedAt:thread.updatedAt??new Date().toISOString(),revision:thread.updatedAt??'0'});if(result){this.transport.send({protocol:'hc/1',type:'task.snapshot',payload:{projectId:project.projectId,threadId:thread.threadId,title:thread.title,status:result.status,resultRevision:result.resultRevision,lastTurnId:result.lastTurnId,resultText:result.resultText,summary:result.resultText?.slice(-384)}});}}if(items.length)this.transport.send({protocol:'hc/1',type:'catalog.snapshot.page',payload:{snapshotId,items}});const count=items.length;this.transport.send({protocol:'hc/1',type:'catalog.snapshot.end',payload:{snapshotId,count}});return count;}
}
function isNewer(candidate?:string,previous?:string){if(!candidate)return false;if(!previous)return true;const c=Date.parse(candidate),p=Date.parse(previous);if(Number.isNaN(c)||Number.isNaN(p))return candidate>previous;return c>p;}
