-- hc/1 initial schema; intentionally independent from the OneTouch website database.
CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, email text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS connectors (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), name text NOT NULL, token_hash text NOT NULL, connection_epoch numeric NOT NULL DEFAULT 1, last_seen_at timestamptz);
CREATE TABLE IF NOT EXISTS devices (id text PRIMARY KEY, name text NOT NULL, bootstrap_credential_hash text NOT NULL, last_seen_at timestamptz);
CREATE TABLE IF NOT EXISTS bindings (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), connector_id text NOT NULL REFERENCES connectors(id), device_id text NOT NULL REFERENCES devices(id), epoch integer NOT NULL, state text NOT NULL, active_task_ref jsonb, selection_revision numeric NOT NULL DEFAULT 0, grants_version numeric NOT NULL DEFAULT 0, UNIQUE(device_id, state));
CREATE TABLE IF NOT EXISTS projects (connector_id text NOT NULL, project_id text NOT NULL, name text NOT NULL, source text NOT NULL, catalog_version numeric NOT NULL, PRIMARY KEY(connector_id, project_id));
CREATE TABLE IF NOT EXISTS tasks (connector_id text NOT NULL, thread_id text NOT NULL, project_id text NOT NULL, title text NOT NULL, status text NOT NULL, revision numeric NOT NULL, updated_at timestamptz NOT NULL, PRIMARY KEY(connector_id, thread_id));
CREATE TABLE IF NOT EXISTS task_grants (binding_id text NOT NULL REFERENCES bindings(id), connector_id text NOT NULL, project_id text NOT NULL, thread_id text NOT NULL, grants_version numeric NOT NULL, PRIMARY KEY(binding_id, connector_id, thread_id));
CREATE TABLE IF NOT EXISTS recordings (id text PRIMARY KEY, binding_id text NOT NULL, epoch integer NOT NULL, target jsonb NOT NULL, selection_revision numeric NOT NULL, client_request_id text NOT NULL, status text NOT NULL, transcript text, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS messages (id text PRIMARY KEY, binding_id text NOT NULL, epoch integer NOT NULL, target jsonb NOT NULL, recording_id text NOT NULL, client_request_id text NOT NULL, status text NOT NULL, execution_id text, command_id text UNIQUE, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS idempotency_records (principal text NOT NULL, operation text NOT NULL, client_request_id text NOT NULL, body_hash text NOT NULL, result jsonb NOT NULL, PRIMARY KEY(principal,operation,client_request_id));
CREATE TABLE IF NOT EXISTS hc_state (id integer PRIMARY KEY CHECK (id=1), payload jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
