import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { randomUUID } from 'node:crypto';
import { PostgresStore } from '../src/pg-store.js';
import { PgBusinessRepository } from '../src/pg-repository.js';
import { migrateAlerts, recordTaskAttention, getAlertSummary, handleAlertRequest } from '../src/pg-alerts.js';

const rid = () => randomUUID().replaceAll('-', '').slice(0, 32);

test('PG alerts baseline, numeric cursor, ack/read idempotency, and binding isolation', async t => {
  const url = process.env.COMPANION_PG_TEST_URL;
  if (!url) return t.skip('COMPANION_PG_TEST_URL not set');
  assert.ok(['127.0.0.1', 'localhost'].includes(new URL(url).hostname));
  const db = new PostgresStore(url);
  t.after(() => db.close());
  const repo = new PgBusinessRepository(db);
  await repo.migrate();
  await migrateAlerts(db);
  const suffix = randomUUID();
  const connector = `alerts-connector-${suffix}`;
  const targetA = { connectorId: connector, projectId: `project-a-${suffix}`, threadId: `thread-a-${suffix}` };
  const targetB = { connectorId: connector, projectId: `project-b-${suffix}`, threadId: `thread-b-${suffix}` };
  const bindingA = await repo.createBinding(`alerts-user-a-${suffix}`, connector, `device-a-${suffix}`, `token-a-${suffix}`);
  const bindingB = await repo.createBinding(`alerts-user-b-${suffix}`, connector, `device-b-${suffix}`, `token-b-${suffix}`);
  await db.pool.query('INSERT INTO hc_grants(binding_id,connector_id,project_id,thread_id) VALUES($1,$2,$3,$4),($1,$2,$5,$6),($7,$2,$5,$6)',
    [bindingA.id, connector, targetA.projectId, targetA.threadId, targetB.projectId, targetB.threadId, bindingB.id]);
  await db.pool.query('INSERT INTO tasks(connector_id,project_id,thread_id,title,status,revision,updated_at) VALUES($1,$2,$3,$4,$5,1,now()),($1,$6,$7,$8,$5,1,now())',
    [connector, targetA.projectId, targetA.threadId, 'A', 'completed', targetB.projectId, targetB.threadId, 'B']);
  await db.pool.query('UPDATE hc_bindings SET active_task_ref=$2 WHERE id=$1', [bindingA.id, JSON.stringify(targetA)]);
  const attention = (input: any) => db.transaction(c => recordTaskAttention(c, input));
  await attention({ ...targetA, turnId: 'turn-a-1', status: 'completed', resultRevision: '1', hadPreviousSnapshot: false });
  await attention({ ...targetB, turnId: 'turn-b-1', status: 'completed', resultRevision: '1', hadPreviousSnapshot: false });
  const summary = async (bindingId: string) => db.transaction(c => getAlertSummary(c, bindingId));
  assert.deepEqual(await summary(bindingA.id), { unreadCount: 0, latestAlertCursor: null });
  const bindingC = await repo.createBinding(`alerts-user-c-${suffix}`, connector, `device-c-${suffix}`, `token-c-${suffix}`);
  await db.pool.query('INSERT INTO hc_grants(binding_id,connector_id,project_id,thread_id) VALUES($1,$2,$3,$4)', [bindingC.id, connector, targetA.projectId, targetA.threadId]);
  await db.pool.query('UPDATE tasks SET revision=2,status=$4 WHERE connector_id=$1 AND project_id=$2 AND thread_id=$3', [connector, targetA.projectId, targetA.threadId, 'completed']);
  await db.pool.query('UPDATE tasks SET revision=2,status=$4 WHERE connector_id=$1 AND project_id=$2 AND thread_id=$3', [connector, targetB.projectId, targetB.threadId, 'waiting_user']);
  await attention({ ...targetA, turnId: 'turn-a-2', status: 'completed', resultRevision: '2', hadPreviousSnapshot: true });
  await attention({ ...targetA, turnId: 'turn-a-2', status: 'completed', resultRevision: '2', hadPreviousSnapshot: true });
  await attention({ ...targetB, turnId: 'turn-b-2', status: 'waiting_user', resultRevision: '2', hadPreviousSnapshot: true });
  const server = createServer((req, res) => {
    const token = (req.headers.authorization ?? '').replace(/^Bearer\s+/i, '');
    void handleAlertRequest(db, token, req, res, new URL(req.url ?? '/', 'http://localhost').pathname);
  });
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise<void>(resolve => server.close(() => resolve())));
  const address = server.address();
  assert.ok(address && typeof address !== 'string');
  const base = `http://127.0.0.1:${address.port}`;
  const get = async (token: string, cursor = '0') => {
    const response = await fetch(`${base}/v1/device/alerts?cursor=${cursor}&limit=1`, { headers: { authorization: `Bearer ${token}` } });
    assert.equal(response.headers.get('content-type'), 'application/json');
    return { response, data: (await response.json()).data };
  };
  const first = await get(bindingA.deviceToken);
  assert.equal(first.response.status, 200);
  assert.equal(first.data.items.length, 1);
  assert.deepEqual(first.data.items[0].target, targetA);
  const second = await get(bindingA.deviceToken, first.data.nextCursor);
  assert.equal(second.response.status, 200, JSON.stringify(second));
  assert.equal(second.data.items.length, 1);
  assert.deepEqual(second.data.items[0].target, targetB);
  const empty = await get(bindingA.deviceToken, second.data.nextCursor);
  assert.deepEqual(empty.data, { items: [], nextCursor: second.data.nextCursor });
  const ackBody = { clientRequestId: rid() };
  const ackPath = `${base}/v1/device/alerts/${encodeURIComponent(first.data.items[0].alertId)}/ack`;
  const ack = await fetch(ackPath, { method: 'POST', headers: { authorization: `Bearer ${bindingA.deviceToken}`, 'content-type': 'application/json' }, body: JSON.stringify(ackBody) });
  assert.equal(ack.status, 200);
  const ackData = (await ack.json()).data;
  const ackRetry = await fetch(ackPath, { method: 'POST', headers: { authorization: `Bearer ${bindingA.deviceToken}`, 'content-type': 'application/json' }, body: JSON.stringify(ackBody) });
  assert.deepEqual((await ackRetry.json()).data, ackData);
  const afterAckRestart = await get(bindingA.deviceToken, '0');
  assert.deepEqual(afterAckRestart.data.items.map((item: any) => item.target), [targetB], 'acknowledged history must not replay from cursor zero');
  const readBody = { clientRequestId: rid(), target: targetA, resultRevision: '2' };
  const read = await fetch(`${base}/v1/device/read`, { method: 'POST', headers: { authorization: `Bearer ${bindingA.deviceToken}`, 'content-type': 'application/json' }, body: JSON.stringify(readBody) });
  assert.equal(read.status, 200);
  assert.equal((await read.json()).data.read, true);
  assert.deepEqual(await summary(bindingA.id), { unreadCount: 1, latestAlertCursor: second.data.nextCursor });
  await attention({ ...targetA, turnId: 'turn-a-2', status: 'completed', resultRevision: '2', hadPreviousSnapshot: true });
  assert.equal((await summary(bindingA.id)).unreadCount, 1, 'same snapshot after read must not resurrect unread');
  await db.pool.query('UPDATE tasks SET revision=3 WHERE connector_id=$1 AND project_id=$2 AND thread_id=$3', [connector, targetA.projectId, targetA.threadId]);
  await attention({ ...targetA, turnId: 'turn-a-3', status: 'completed', resultRevision: '3', hadPreviousSnapshot: true });
  assert.equal((await summary(bindingC.id)).unreadCount, 1, 'new binding baselines existing history, then alerts on a later revision');
  const afterNewAlert = await get(bindingA.deviceToken, afterAckRestart.data.nextCursor);
  assert.deepEqual(afterNewAlert.data.items[0].target, targetA, 'new alert remains available after acknowledged history');
  await db.pool.query('DELETE FROM hc_grants WHERE binding_id=$1 AND project_id=$2 AND thread_id=$3', [bindingA.id, targetB.projectId, targetB.threadId]);
  const afterGrantRemoval = await get(bindingA.deviceToken, '0');
  assert.deepEqual(afterGrantRemoval.data.items.map((item: any) => item.target), [targetA], 'revoked task grant removes old alert from listing');
  assert.equal((await summary(bindingA.id)).unreadCount, 1, 'revoked task grant is excluded from unread summary');
  const crossAck = await fetch(ackPath, { method: 'POST', headers: { authorization: `Bearer ${bindingB.deviceToken}`, 'content-type': 'application/json' }, body: JSON.stringify({ clientRequestId: rid() }) });
  assert.equal(crossAck.status, 404);
  const active = await db.pool.query('SELECT active_task_ref FROM hc_bindings WHERE id=$1', [bindingA.id]);
  assert.deepEqual(active.rows[0].active_task_ref, targetA, 'alerts never change activeTaskRef');
});
