import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import WebSocket from 'ws';
import { createPgApp } from '../src/pg-app.js';
import { PostgresStore } from '../src/pg-store.js';
import { PgBusinessRepository } from '../src/pg-repository.js';
import { attachPgChannel, migratePgChannel } from '../src/pg-channel.js';

test('PG hello capabilities reach the real device task HTTP route with epoch isolation', async t => {
  const url = process.env.COMPANION_PG_TEST_URL;
  if (!url) return t.skip('COMPANION_PG_TEST_URL not set');
  const db = new PostgresStore(url), repo = new PgBusinessRepository(db);
  await repo.migrate(); await migratePgChannel(db);
  const suffix = randomUUID(), connector = `cap-${suffix}`, token = `cap-token-${suffix}`;
  const binding = `cap-binding-${suffix}`, deviceToken = `cap-device-${suffix}`;
  const project = `cap-project-${suffix}`, thread = `cap-thread-${suffix}`;
  await db.pool.query('INSERT INTO hc_connectors(id,email,name,token_hash) VALUES($1,$2,$3,$4)', [connector, `cap-${suffix}@test.invalid`, 'capability', createHash('sha256').update(token).digest('hex')]);
  await db.pool.query("INSERT INTO hc_bindings(id,user_id,device_id,connector_id,epoch,state,device_token) VALUES($1,$2,$3,$4,1,'active',$5)", [binding, `cap-user-${suffix}`, `cap-device-id-${suffix}`, connector, deviceToken]);
  await db.pool.query('INSERT INTO projects(connector_id,project_id,name,source) VALUES($1,$2,$3,$4)', [connector, project, 'Capability project', 'local']);
  await db.pool.query('INSERT INTO tasks(connector_id,thread_id,project_id,title,status,revision,updated_at) VALUES($1,$2,$3,$4,$5,7,now())', [connector, thread, project, 'Capability task', 'idle']);
  await db.pool.query('INSERT INTO hc_grants(binding_id,connector_id,project_id,thread_id) VALUES($1,$2,$3,$4)', [binding, connector, project, thread]);
  const app = createPgApp(db); attachPgChannel(app, db); await new Promise<void>(resolve => app.listen(0, '127.0.0.1', resolve));
  let ws1: WebSocket | undefined, ws2: WebSocket | undefined;
  const closeWs = async (ws?: WebSocket) => { if (!ws || ws.readyState === WebSocket.CLOSED) return; await new Promise<void>(resolve => { ws.once('close', () => resolve()); ws.close(); }); };
  t.after(async () => {
    await closeWs(ws1); await closeWs(ws2);
    await new Promise<void>(resolve => app.close(() => resolve()));
    await db.pool.query('DELETE FROM hc_grants WHERE binding_id=$1', [binding]);
    await db.pool.query('DELETE FROM tasks WHERE connector_id=$1', [connector]);
    await db.pool.query('DELETE FROM projects WHERE connector_id=$1', [connector]);
    await db.pool.query('DELETE FROM hc_bindings WHERE id=$1', [binding]);
    await db.pool.query('DELETE FROM hc_connectors WHERE id=$1', [connector]);
    await db.close();
  });
  const port = (app.address() as any).port;
  const detail = async () => (await (await fetch(`http://127.0.0.1:${port}/v1/device/task?threadId=${thread}&projectId=${project}`, { headers: { authorization: `Bearer ${deviceToken}` } })).json() as any).data;
  const waitFor = async (predicate: () => Promise<boolean>) => { const deadline = Date.now() + 2000; while (Date.now() < deadline) { if (await predicate()) return; await new Promise(resolve => setTimeout(resolve, 10)); } throw new Error('CAPABILITIES_TIMEOUT'); };
  const connect = () => new WebSocket(`ws://127.0.0.1:${port}/v1/connectors/channel`, { headers: { authorization: `Bearer ${token}`, 'x-connector-id': connector } });
  ws1 = connect(); const welcome1 = await new Promise<any>((resolve, reject) => { ws1!.on('message', raw => { const event = JSON.parse(raw.toString()); if (event.type === 'connector.welcome') resolve(event); }); ws1!.once('error', reject); });
  const before = await detail();
  assert.equal(before.capabilities.canSend, 'unknown');
  ws1.send(JSON.stringify({ protocol: 'hc/1', type: 'connector.hello', payload: { capabilities: { list: true, read: true, enqueue: true, accountContextDetection: false, nativeApproval: true } } }));
  await waitFor(async () => (await detail()).capabilities.canSend === false);
  assert.equal((await detail()).capabilities.nativeApproval, false);
  ws2 = connect(); const welcome2 = await new Promise<any>((resolve, reject) => { ws2!.on('message', raw => { const event = JSON.parse(raw.toString()); if (event.type === 'connector.welcome') resolve(event); }); ws2!.once('error', reject); });
  assert.ok(Number(welcome2.payload.connectionEpoch) > Number(welcome1.payload.connectionEpoch));
  await waitFor(async () => ws1!.readyState === WebSocket.CLOSED);
  ws2.send(JSON.stringify({ protocol: 'hc/1', type: 'connector.hello', payload: { capabilities: { list: true, read: true, enqueue: true, accountContextDetection: true, nativeApproval: true } } }));
  await waitFor(async () => (await detail()).capabilities.canSend === true);
  assert.deepEqual((await detail()).capabilities, { list: true, read: true, enqueue: true, accountContextDetection: true, canSend: true, nativeApproval: false });
});
