import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { PostgresStore } from '../src/pg-store.js';
import { PgBusinessRepository } from '../src/pg-repository.js';
import { createPgApp } from '../src/pg-app.js';
const run = promisify(execFile);

test('PG connector browser login is pending, approval-bound, and poll-idempotent', async (t) => {
  const url = process.env.COMPANION_PG_TEST_URL;
  if (!url) return t.skip('COMPANION_PG_TEST_URL not set');
  const db = new PostgresStore(url);
  const repo = new PgBusinessRepository(db);
  await repo.migrate();
  await repo.migrateAuth();
  const mail = { code: '', async send(_email: string, code: string) { this.code = code; } };
  const email = `connector-login-${Date.now()}@test.invalid`;
  const app = createPgApp(db, { publicBaseUrl: 'https://companion.example.test', mailProvider: mail });
  await new Promise<void>((resolve) => app.listen(0, '127.0.0.1', resolve));
  t.after(async () => { await new Promise<void>((resolve) => app.close(() => resolve())); await db.close(); });
  const port = (app.address() as any).port;
  const call = (path: string, body?: unknown, token?: string) => fetch(`http://127.0.0.1:${port}${path}`, {
    method: 'POST', headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) },
    body: JSON.stringify(body ?? {}),
  });
  const started = await call('/v1/connector-login/start');
  assert.equal(started.status, 200);
  const start = (await started.json() as any).data;
  assert.match(start.browserUrl, /\/v1\/connector-login\/.*\/browser$/);
  assert.ok(start.pollSecret);
  const browser = await fetch(start.browserUrl.replace('https://companion.example.test', `http://127.0.0.1:${port}`));
  assert.equal(browser.status, 200);
  assert.match(await browser.text(), /确认连接/);
  assert.equal((await (await call(`/v1/connector-login/${start.loginId}/poll`, { pollSecret: 'wrong' })).status), 401);
  assert.equal((await (await call(`/v1/connector-login/${start.loginId}/poll`, { pollSecret: start.pollSecret })).json() as any).data.status, 'pending');
  const sessionResponse = await call('/v1/auth/email/start', { email });
  assert.equal(sessionResponse.status, 200);
  const verified = await call('/v1/auth/email/verify', { email, code: mail.code });
  const session = (await verified.json() as any).data;
  assert.equal((await call(`/v1/connector-login/${start.loginId}/approve`, { confirm: false }, session.sessionToken)).status, 400);
  const firstApproval = await call(`/v1/connector-login/${start.loginId}/approve`, { confirm: true }, session.sessionToken);
  assert.equal(firstApproval.status, 200);
  assert.equal('token' in ((await firstApproval.json() as any).data), false);
  const approvedResponse = await call(`/v1/connector-login/${start.loginId}/approve`, { confirm: true }, session.sessionToken);
  assert.equal(approvedResponse.status, 200);
  assert.equal('token' in ((await approvedResponse.json() as any).data), false);
  const first = (await (await call(`/v1/connector-login/${start.loginId}/poll`, { pollSecret: start.pollSecret })).json() as any).data;
  const second = (await (await call(`/v1/connector-login/${start.loginId}/poll`, { pollSecret: start.pollSecret })).json() as any).data;
  assert.equal(first.status, 'approved');
  assert.deepEqual(second, first);
  const row = await db.pool.query('SELECT poll_secret_hash,connector_token_hash FROM hc_connector_logins WHERE id=$1', [start.loginId]);
  assert.equal(row.rows[0].poll_secret_hash, createHash('sha256').update(start.pollSecret).digest('hex'));
  assert.equal(row.rows[0].connector_token_hash, createHash('sha256').update(first.token).digest('hex'));

  const otherEmail = `connector-login-other-${Date.now()}@test.invalid`;
  await call('/v1/auth/email/start', { email: otherEmail });
  const otherSession = (await (await call('/v1/auth/email/verify', { email: otherEmail, code: mail.code })).json() as any).data.sessionToken;
  assert.equal((await call(`/v1/connector-login/${start.loginId}/approve`, { confirm: true }, otherSession)).status, 401);

  const cli = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'connector', 'dist', 'cli.js');
  const configDir = await mkdtemp(join(tmpdir(), 'hc-login-cli-'));
  t.after(() => rm(configDir, { recursive: true, force: true }));
  const config = join(configDir, 'config.json');
  const base = ['--config', config, '--base-url', `http://127.0.0.1:${port}`];
  const authStart = JSON.parse((await run(process.execPath, [cli, 'auth', 'start', ...base])).stdout).data;
  assert.ok(authStart.loginId);
  const cliPoll = JSON.parse((await run(process.execPath, [cli, 'auth', 'poll', ...base])).stdout).data;
  assert.equal(cliPoll.status, 'pending');
  assert.equal((await call(`/v1/connector-login/${authStart.loginId}/approve`, { confirm: true }, session.sessionToken)).status, 200);
  const approvedPoll = JSON.parse((await run(process.execPath, [cli, 'auth', 'poll', ...base])).stdout).data;
  assert.equal(approvedPoll.status, 'approved');
  assert.equal('token' in approvedPoll, false);
  const cliConfig = JSON.parse(await readFile(config, 'utf8'));
  assert.ok(cliConfig.token);
});

test('PG connector demo login consumes the configured code once and returns a SaaS session', async (t) => {
  const url = process.env.COMPANION_PG_TEST_URL;
  if (!url) return t.skip('COMPANION_PG_TEST_URL not set');
  const previousEnabled = process.env.HC_DEMO_LOGIN_ENABLED;
  const previousEmail = process.env.HC_DEMO_LOGIN_EMAIL;
  const previousCode = process.env.HC_DEMO_LOGIN_CODE;
  process.env.HC_DEMO_LOGIN_ENABLED = 'true';
  process.env.HC_DEMO_LOGIN_EMAIL = `demo-${Date.now()}@companion.invalid`;
  process.env.HC_DEMO_LOGIN_CODE = `DEMO-${Date.now()}`;
  t.after(() => {
    if (previousEnabled === undefined) delete process.env.HC_DEMO_LOGIN_ENABLED; else process.env.HC_DEMO_LOGIN_ENABLED = previousEnabled;
    if (previousEmail === undefined) delete process.env.HC_DEMO_LOGIN_EMAIL; else process.env.HC_DEMO_LOGIN_EMAIL = previousEmail;
    if (previousCode === undefined) delete process.env.HC_DEMO_LOGIN_CODE; else process.env.HC_DEMO_LOGIN_CODE = previousCode;
  });
  const db = new PostgresStore(url);
  const repo = new PgBusinessRepository(db);
  await repo.migrate(); await repo.migrateAuth();
  const app = createPgApp(db, { publicBaseUrl: 'https://companion.example.test' });
  await new Promise<void>((resolve) => app.listen(0, '127.0.0.1', resolve));
  t.after(async () => { await new Promise<void>((resolve) => app.close(() => resolve())); await db.close(); });
  const port = (app.address() as any).port;
  const call = (path: string, body?: unknown) => fetch(`http://127.0.0.1:${port}${path}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body ?? {}) });
  const started = await call('/v1/connector-login/start');
  assert.equal(started.status, 200);
  const start = (await started.json() as any).data;
  assert.equal(start.demoCode, undefined);
  const stored = await db.pool.query('SELECT demo_code_hash,demo_code_consumed_at FROM hc_connector_logins WHERE id=$1', [start.loginId]);
  assert.notEqual(stored.rows[0].demo_code_hash, start.demoCode);
  assert.equal(stored.rows[0].demo_code_consumed_at, null);
  const browser = await fetch(`http://127.0.0.1:${port}/v1/connector-login/${start.loginId}/browser`);
  assert.match(await browser.text(), /演示码登录/);
  const approved = await call(`/v1/connector-login/${start.loginId}/demo-approve`, { code: process.env.HC_DEMO_LOGIN_CODE, confirm: true });
  assert.equal(approved.status, 200);
  const approval = (await approved.json() as any).data;
  assert.equal(approval.status, 'approved');
  assert.match(approval.sessionToken, /^sess-/);
  const second = await call(`/v1/connector-login/${start.loginId}/demo-approve`, { code: process.env.HC_DEMO_LOGIN_CODE, confirm: true });
  assert.equal(second.status, 401);
  const polled = (await (await call(`/v1/connector-login/${start.loginId}/poll`, { pollSecret: start.pollSecret })).json() as any).data;
  assert.equal(polled.status, 'approved');
  const consumed = await db.pool.query('SELECT demo_code_consumed_at FROM hc_connector_logins WHERE id=$1', [start.loginId]);
  assert.ok(consumed.rows[0].demo_code_consumed_at);
  const secondStart = (await (await call('/v1/connector-login/start')).json() as any).data;
  const secondAttempt = await call(`/v1/connector-login/${secondStart.loginId}/demo-approve`, { code: process.env.HC_DEMO_LOGIN_CODE, confirm: true });
  assert.equal(secondAttempt.status, 401);
});
