import test from 'node:test';
import assert from 'node:assert/strict';
import { CompanionService } from '../src/service.js';
import { fixtureCatalog, fixtureRefs } from '@companion/protocol/fixtures';

const rid=(n:number)=>n.toString(16).padStart(32,'0');
function setup(){const s=new CompanionService(),u=s.store.addUser('USER@example.test'),{connector,token}=s.register(u.id),{device}=s.createDevice();const projects=fixtureCatalog.projects.map(p=>({...p,connectorId:connector.id}));const tasks=fixtureCatalog.tasks.map(t=>({...t,connectorId:connector.id}));s.store.seedCatalog(connector.id,projects,tasks);const refs={a:{...fixtureRefs.a,connectorId:connector.id},b:{...fixtureRefs.b,connectorId:connector.id},c:{...fixtureRefs.c,connectorId:connector.id}};const b=s.bind(u.id,connector.id,device.id,rid(1));return {s,b,connector,token,refs};}
test('catalog, selection, recording and message preserve frozen TaskRef',()=>{const {s,b,refs}=setup();assert.equal(s.setGrants(b.id,[refs.a,refs.c],'0',rid(2)).grants.length,2);const selected=s.select(b.id,refs.a,'0',rid(3));const r=s.createRecording(b.id,refs.a,selected.selectionRevision,rid(4),'继续处理 A');const m=s.submitMessage(b.id,r.id,refs.a,selected.selectionRevision,rid(5));assert.deepEqual(m.target,refs.a);assert.equal(s.store.commands.get(m.commandId!)?.text,'继续处理 A');});
test('selection CAS and revoke reject stale operations',()=>{const {s,b,refs}=setup();s.setGrants(b.id,[refs.a],'0',rid(2));s.select(b.id,refs.a,'0',rid(3));assert.throws(()=>s.select(b.id,refs.a,'0',rid(4)),/SELECTION_CONFLICT/);s.revoke(b.id,rid(5));assert.throws(()=>s.catalog(b.id,'projects'),/BINDING_REVOKED/);});
test('command claim allocates one execution id and is repeat-safe',()=>{const {s,b,connector,refs}=setup();s.setGrants(b.id,[refs.a],'0',rid(2));const sel=s.select(b.id,refs.a,'0',rid(3));const rec=s.createRecording(b.id,refs.a,sel.selectionRevision,rid(4),'hello');const msg=s.submitMessage(b.id,rec.id,refs.a,sel.selectionRevision,rid(5));const c=s.claimCommand(msg.commandId!,connector.id,connector.connectionEpoch,rid(6));assert.ok(c.executionId);assert.equal(s.claimCommand(msg.commandId!,connector.id,connector.connectionEpoch,rid(7)).executionId,c.executionId);});
test('empty ASR text never becomes a chat message',()=>{const {s,b,refs}=setup();s.setGrants(b.id,[refs.a],'0',rid(2));const sel=s.select(b.id,refs.a,'0',rid(3));const rec=s.createRecording(b.id,refs.a,sel.selectionRevision,rid(4),'   ');assert.throws(()=>s.submitMessage(b.id,rec.id,refs.a,sel.selectionRevision,rid(5)),/ASR_FAILED/);});
