import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { randomUUID } from 'node:crypto';
import { apiError, apiOk, type TaskRef } from '@companion/protocol';
import { CompanionService } from './service.js';
import { attachConnectorChannel } from './channel.js';

async function body(req:IncomingMessage){let s='';for await(const chunk of req)s+=chunk;return s?JSON.parse(s):{};}
function write(res:ServerResponse,status:number,data:unknown){const encoded=JSON.stringify(data);if(Buffer.byteLength(encoded,'utf8')>16384){res.statusCode=413;res.setHeader('content-type','application/json');return res.end(JSON.stringify({protocol:'hc/1',requestId:'00000000000000000000000000000000',error:{code:'PAYLOAD_TOO_LARGE',message:'JSON response exceeds 16 KiB',retryable:false}}));}res.statusCode=status;res.setHeader('content-type','application/json');res.end(encoded);}
function auth(req:IncomingMessage,service:CompanionService){const token=(req.headers.authorization??'').replace(/^Bearer\s+/,'');for(const c of service.store.connectors.values())if(c.tokenHash&&service.store.connectors.get(c.id)?.tokenHash){/* token hashes are intentionally not reversible; tests use x-connector-id */}return req.headers['x-connector-id']?.toString();}
function errStatus(error:unknown){const code=error instanceof Error?error.message:'INVALID_REQUEST';return code==='CONFIG_MISSING'?503:code==='UNAUTHORIZED'?401:code==='NOT_FOUND'?404:code==='TARGET_NOT_GRANTED'?403:code==='BINDING_REVOKED'?401:code==='PAYLOAD_TOO_LARGE'?413:code==='SELECTION_CONFLICT'||code==='IDEMPOTENCY_CONFLICT'||code==='CATALOG_CHANGED'?409:code==='BUSY'?429:400;}
function bearer(req:IncomingMessage){return (req.headers.authorization??'').replace(/^Bearer\s+/,'');}
function bindingAuth(req:IncomingMessage,service:CompanionService,bindingId:string){const b=service.store.bindings.get(bindingId);if(!b||b.state!=='active')throw new Error('BINDING_REVOKED');if(bearer(req)!==b.deviceToken)throw new Error('UNAUTHORIZED');return b;}
function grantAuth(req:IncomingMessage,service:CompanionService,bindingId:string){const b=service.store.bindings.get(bindingId);if(!b||b.state!=='active')throw new Error('BINDING_REVOKED');const token=bearer(req);try{if(service.userFromSession(token).id===b.userId)return b;}catch{}try{if(service.connectorFromToken(token).id===b.connectorId)return b;}catch{}throw new Error('UNAUTHORIZED');}

export function createApp(service=new CompanionService(),options:{testMode?:boolean}={}){
  if(!options.testMode && service instanceof CompanionService && process.env.NODE_ENV==='production') throw new Error('Production HTTP requires a PG-backed service');
  const server=createServer(async(req,res)=>{const requestId=req.headers['x-request-id']?.toString()??randomUUID().replaceAll('-','').slice(0,32);const url=new URL(req.url??'/',`http://${req.headers.host??'localhost'}`);try{
    if(req.method==='GET'&&url.pathname==='/healthz')return write(res,200,apiOk(requestId,{status:'ok',protocol:'hc/1'}));
    if(req.method==='POST'&&url.pathname==='/v1/auth/email/start'){if(!options.testMode&&!process.env.EMAIL_PROVIDER)throw new Error('CONFIG_MISSING');const x=await body(req);return write(res,200,apiOk(requestId,service.startEmail(x.email??'')));}
    if(req.method==='POST'&&url.pathname==='/v1/auth/email/verify'){const x=await body(req);return write(res,200,apiOk(requestId,service.verifyEmail(x.email??'',x.code??'')));}
    if(options.testMode&&req.method==='POST'&&url.pathname==='/v1/test/users'){const x=await body(req);const u=service.store.addUser(x.email??`test-${randomUUID()}@invalid`);return write(res,201,apiOk(requestId,{userId:u.id,email:u.email}));}
    if(req.method==='POST'&&url.pathname==='/v1/connector-login/start'){const out=service.startConnectorLogin();return write(res,201,apiOk(requestId,out));}
    const lm=url.pathname.match(/^\/v1\/connector-login\/([^/]+)\/(approve|poll)$/);if(lm&&req.method==='POST'){const x=await body(req);const out=lm[2]==='approve'?service.approveConnectorLogin(lm[1],x.userId):service.pollConnectorLogin(lm[1],x.pollSecret);return write(res,200,apiOk(requestId,out));}
    if(req.method==='POST'&&url.pathname==='/v1/connectors/register'){const user=service.userFromSession(bearer(req));const x=await body(req);const out=service.register(user.id,x.name);return write(res,201,apiOk(requestId,{connectorId:out.connector.id,token:out.token}));}
    if(req.method==='POST'&&url.pathname==='/v1/device-pairings'){const device=service.deviceFromBootstrap(bearer(req));const x=await body(req);const c=service.connectorFromToken(x.connectorToken);return write(res,201,apiOk(requestId,service.startDevicePairing(device.id,c.id,x.clientRequestId)));}
    const dpm=url.pathname.match(/^\/v1\/device-pairings\/([^/]+)\/(claim|poll|confirm)$/);if(dpm&&req.method==='POST'){const x=await body(req);if(dpm[2]==='claim'){const user=service.userFromSession(bearer(req));return write(res,200,apiOk(requestId,service.claimDevicePairing(dpm[1],x.code,user.id)));}const p=service.store.devicePairings.get(dpm[1]);if(!p)throw new Error('NOT_FOUND');if(dpm[2]==='poll'||dpm[2]==='confirm'){service.deviceFromBootstrap(bearer(req));const out=dpm[2]==='poll'?service.pollDevicePairing(dpm[1],x.pollSecret):service.confirmDevicePairing(dpm[1],x.pollSecret,x.clientRequestId);return write(res,200,apiOk(requestId,out));}}
    if(req.method==='POST'&&url.pathname==='/v1/device/binding/recover'){const d=service.deviceFromBootstrap(bearer(req));return write(res,200,apiOk(requestId,service.recoverBinding(d.id)));}
    if(req.method==='GET'&&url.pathname==='/v1/devices'){const user=service.userFromSession(bearer(req));return write(res,200,apiOk(requestId,service.devices(user.id)));}
    if(options.testMode&&req.method==='POST'&&url.pathname==='/v1/test/devices'){const x=await body(req);const out=service.createDevice(x.name);return write(res,201,apiOk(requestId,{deviceId:out.device.id,bootstrap:out.bootstrap}));}
    if(options.testMode&&req.method==='POST'&&url.pathname==='/v1/test/bind'){const x=await body(req);service.connectorFromToken(bearer(req));service.deviceFromBootstrap(x.bootstrap);const b=service.bind(x.userId,x.connectorId,x.deviceId,x.clientRequestId);return write(res,201,apiOk(requestId,b));}
    if(req.method==='POST'&&url.pathname==='/v1/pairings'){const c=service.connectorFromToken(bearer(req));const x=await body(req);if(x.connectorId!==c.id)throw new Error('UNAUTHORIZED');return write(res,201,apiOk(requestId,service.createPairing(c.id,x.deviceId,x.clientRequestId)));}
    const pair=url.pathname.match(/^\/v1\/pairings\/([^/]+)\/claim$/);if(pair&&req.method==='POST'){const user=service.userFromSession(bearer(req));const x=await body(req);return write(res,200,apiOk(requestId,service.claimPairing(pair[1],x.code,user.id)));}
    const match=url.pathname.match(/^\/v1\/bindings\/([^/]+)\/task-grants$/);if(match&&req.method==='PUT'){grantAuth(req,service,match[1]);const x=await body(req);return write(res,200,apiOk(requestId,service.setGrants(match[1],x.grants??[],x.expectedGrantsVersion??'0',x.clientRequestId)));}
    if(match&&req.method==='GET'){const b=grantAuth(req,service,match[1]);return write(res,200,apiOk(requestId,{grants:[...(service.store.grants.get(b.id)??[])],grantsVersion:b.grantsVersion}));}
    const bm=url.pathname.match(/^\/v1\/bindings\/([^/]+)$/);if(bm&&req.method==='DELETE'){bindingAuth(req,service,bm[1]);return write(res,200,apiOk(requestId,service.revoke(bm[1],(await body(req)).clientRequestId)));}
    const pm=url.pathname.match(/^\/v1\/device\/(projects|tasks)$/);if(pm&&req.method==='GET'){const binding=url.searchParams.get('bindingId');if(!binding)throw new Error('UNBOUND');bindingAuth(req,service,binding);const out=service.catalog(binding,pm[1] as 'projects'|'tasks',url.searchParams.get('projectId')??undefined,Number(url.searchParams.get('limit')??5),Number(url.searchParams.get('cursor')??0));return write(res,200,apiOk(requestId,out));}
    if(req.method==='POST'&&url.pathname==='/v1/device/selection'){const x=await body(req);bindingAuth(req,service,x.bindingId);return write(res,200,apiOk(requestId,service.select(x.bindingId,x.target as TaskRef,x.expectedSelectionRevision,x.clientRequestId)));}
    if(req.method==='POST'&&url.pathname==='/v1/device/recordings'){const x=await body(req);bindingAuth(req,service,x.bindingId);if((x.transcript??'').length>4096)throw new Error('PAYLOAD_TOO_LARGE');return write(res,202,apiOk(requestId,service.createRecording(x.bindingId,x.target,x.selectionRevision,x.clientRequestId,x.transcript??'')));}
    if(req.method==='POST'&&url.pathname==='/v1/device/messages'){const x=await body(req);bindingAuth(req,service,x.bindingId);return write(res,202,apiOk(requestId,service.submitMessage(x.bindingId,x.recordingId,x.target,x.selectionRevision,x.clientRequestId)));}
    const cm=url.pathname.match(/^\/v1\/connectors\/commands\/([^/]+)\/claim$/);if(cm&&req.method==='POST'){const x=await body(req);return write(res,200,apiOk(requestId,service.claimCommand(cm[1],x.connectorId,x.connectionEpoch,x.clientRequestId)));}
    return write(res,404,apiError(requestId,'NOT_FOUND','route not found'));
  }catch(e){const code=(e instanceof Error?e.message:'INVALID_REQUEST') as any;return write(res,errStatus(e),apiError(requestId,code,code));}});const channel=attachConnectorChannel(server,service);return {server,service,channel};
}
