import type { Server } from 'node:http';
import { WebSocketServer, type WebSocket } from 'ws';
import { randomUUID } from 'node:crypto';
import { PROTOCOL, nowIso } from '@companion/protocol';
import { CompanionService } from './service.js';

/** Connector channel: WSS only transports durable events; command execution still requires claim(). */
export function attachConnectorChannel(server:Server,service:CompanionService){
  const wss=new WebSocketServer({noServer:true});
  server.on('upgrade',(req,socket,head)=>{const url=new URL(req.url??'/',`http://${req.headers.host??'localhost'}`);if(url.pathname!=='/v1/connectors/channel'){socket.destroy();return;}let connectorId='';try{connectorId=service.connectorFromToken((req.headers.authorization??'').replace(/^Bearer\s+/, '')).id;}catch{socket.destroy();return;}wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,connectorId));});
  wss.on('connection',(ws:WebSocket,connectorId:string)=>{const conn=service.store.connectors.get(connectorId)!;conn.online=true;conn.connectionEpoch=String(Number(conn.connectionEpoch)+1);let seq=0;const send=(type:string,payload:Record<string,unknown>)=>ws.send(JSON.stringify({protocol:PROTOCOL,eventId:`evt-${randomUUID()}`,seq:String(++seq),type,connectorId,sentAt:nowIso(),payload}));send('connector.welcome',{connectionEpoch:conn.connectionEpoch,serverEpoch:'saas-local',grantsVersion:'0'});for(const c of service.store.commands.values())if(c.connectorId===connectorId&&c.state==='available')send('command.available',{commandId:c.commandId});ws.on('message',raw=>{try{const msg=JSON.parse(raw.toString());if(msg.type==='connector.hello')send('connector.welcome',{connectionEpoch:conn.connectionEpoch,serverEpoch:'saas-local',grantsVersion:'0'});if(msg.type==='heartbeat')send('heartbeat.ack',{seq:msg.seq??'0'});if(msg.type==='catalog.snapshot.begin'||msg.type==='catalog.snapshot.page'||msg.type==='catalog.snapshot.end')send('catalog.ack',{snapshotId:msg.payload?.snapshotId??'',type:msg.type});if(msg.type==='task.snapshot'){const p=msg.payload??{};if(p.threadId&&p.projectId){const key=`${connectorId}:${p.threadId}`,old=service.store.tasks.get(key);service.store.tasks.set(key,{connectorId,projectId:String(p.projectId),threadId:String(p.threadId),title:String(p.title??old?.title??p.threadId),titleSource:'codex',status:(p.status??old?.status??'unknown'),unread:false,revision:String(p.revision??old?.revision??'0'),updatedAt:nowIso()});}}if(msg.type?.startsWith('command.')){const p=msg.payload??{},c=service.store.commands.get(String(p.commandId??''));if(c&&['queued','running','completed','failed','uncertain'].includes(msg.type.slice(8))){c.state=msg.type.slice(8) as any;const m=service.store.messages.get(c.messageId);if(m)m.status=c.state as any;}}if(msg.type==='ack'){} }catch{ws.close(1003,'invalid JSON');}});ws.on('close',()=>{conn.online=false;});});return wss;
}
