import { randomUUID } from 'node:crypto';
import type { Grant, TaskRef } from '@companion/protocol';
import { assertClientRequestId, nowIso } from '@companion/protocol';
import { MemoryStore } from './store.js';

export class CompanionService {
  constructor(public store=new MemoryStore()) {}
  startEmail(email:string){const normalized=email.trim().toLowerCase();const code=String(Math.floor(100000+Math.random()*900000));this.store.emailCodes.set(normalized,code);return {status:'sent',testAdapter:process.env.NODE_ENV==='test'};}
  verifyEmail(email:string,code:string){const normalized=email.trim().toLowerCase();if(this.store.emailCodes.get(normalized)!==code)throw new Error('UNAUTHORIZED');let user=[...this.store.users.values()].find(x=>x.email===normalized);if(!user)user=this.store.addUser(normalized);const token=`sess-${randomUUID()}${randomUUID()}`;this.store.sessions.set(token,user.id);return {sessionToken:token,userId:user.id};}
  userFromSession(token:string){const id=this.store.sessions.get(token);if(!id)throw new Error('UNAUTHORIZED');return this.store.users.get(id)!;}
  connectorFromToken(token:string){for(const [id,secret] of this.store.connectorSecrets)if(secret===token)return this.store.connectors.get(id)!;throw new Error('UNAUTHORIZED');}
  deviceFromBootstrap(token:string){for(const d of this.store.devices.values())if(d.bootstrap===token)return d;throw new Error('UNAUTHORIZED');}
  startDevicePairing(deviceId:string,connectorId:string,requestId:string){assertClientRequestId(requestId);this.deviceFromBootstrap(this.store.devices.get(deviceId)?.bootstrap??'');if(!this.store.connectors.has(connectorId))throw new Error('NOT_FOUND');const id=`dp-${randomUUID()}`,pollSecret=randomUUID()+randomUUID(),expiresAt=new Date(Date.now()+300000).toISOString();this.store.devicePairings.set(id,{id,deviceId,connectorId,pollSecret,expiresAt});return {devicePairingId:id,pollSecret,qrUrl:`/pair?devicePairingId=${id}`,expiresAt};}
  claimDevicePairing(id:string,code:string,userId:string){const p=this.store.devicePairings.get(id);const c=p&&this.store.connectors.get(p.connectorId);if(!p||!c||c.userId!==userId||Date.parse(p.expiresAt)<Date.now())throw new Error('UNAUTHORIZED');p.code=code;p.claimedUserId=userId;return {status:'claimed',deviceId:p.deviceId,connectorId:p.connectorId};}
  pollDevicePairing(id:string,pollSecret:string){const p=this.store.devicePairings.get(id);if(!p||p.pollSecret!==pollSecret||Date.parse(p.expiresAt)<Date.now())throw new Error('UNAUTHORIZED');return p.confirmedBindingId?{status:'confirmed',bindingId:p.confirmedBindingId}:{status:p.claimedUserId?'claimed':'pending'};}
  confirmDevicePairing(id:string,pollSecret:string,requestId:string){assertClientRequestId(requestId);const p=this.store.devicePairings.get(id);if(!p||p.pollSecret!==pollSecret||!p.claimedUserId)throw new Error('UNAUTHORIZED');if(p.confirmedBindingId)return this.store.bindings.get(p.confirmedBindingId)!;const b=this.bind(p.claimedUserId,p.connectorId,p.deviceId,requestId);p.confirmedBindingId=b.id;return b;}
  recoverBinding(deviceId:string){const b=[...this.store.bindings.values()].find(x=>x.deviceId===deviceId&&x.state==='active');return b?{status:'bound',bindingId:b.id,epoch:b.epoch,deviceToken:b.deviceToken}:{status:'unbound'};}
  devices(userId:string){return [...this.store.bindings.values()].filter(b=>b.userId===userId).map(b=>({deviceId:b.deviceId,bindingId:b.id,epoch:b.epoch,state:b.state,name:this.store.devices.get(b.deviceId)?.name}));}
  renameDevice(userId:string,deviceId:string,name:string){const d=this.store.devices.get(deviceId);if(!d||![...this.store.bindings.values()].some(b=>b.userId===userId&&b.deviceId===deviceId&&b.state==='active'))throw new Error('UNAUTHORIZED');d.name=name;return d;}
  startConnectorLogin(){const id=`login-${randomUUID()}`,pollSecret=randomUUID()+randomUUID();const row={id,pollSecret,expiresAt:new Date(Date.now()+600000).toISOString()};this.store.loginTransactions.set(id,row);return {loginId:id,pollSecret,expiresAt:row.expiresAt,browserUrl:`/login?loginId=${id}`};}
  approveConnectorLogin(loginId:string,userId:string){const row=this.store.loginTransactions.get(loginId);if(!row||Date.parse(row.expiresAt)<Date.now())throw new Error('NOT_FOUND');if(!this.store.users.has(userId))throw new Error('UNAUTHORIZED');row.userId=userId;row.approved=true;return {status:'approved'};}
  pollConnectorLogin(loginId:string,pollSecret:string){const row=this.store.loginTransactions.get(loginId);if(!row||row.pollSecret!==pollSecret||Date.parse(row.expiresAt)<Date.now())throw new Error('UNAUTHORIZED');if(!row.approved||!row.userId)return {status:'pending'};if(!row.token){const out=this.register(row.userId);row.token=out.token;row.pollSecret='consumed';return {status:'approved',connectorId:out.connector.id,token:out.token};}return {status:'approved'};}
  register(userId:string,name?:string){return this.store.addConnector(userId,name);}
  registerAnonymous(clientId:string,name?:string){if(!/^[A-Za-z0-9_-]{16,128}$/.test(clientId))throw new Error('INVALID_REQUEST');return this.store.addAnonymousConnector(clientId,name);}
  createDevice(name?:string){return this.store.addDevice(name);}
  createPairing(connectorId:string,deviceId:string,requestId:string){assertClientRequestId(requestId);if(!this.store.connectors.has(connectorId)||!this.store.devices.has(deviceId))throw new Error('NOT_FOUND');const id=`pair-${randomUUID()}`,code=String(Math.floor(100000+Math.random()*900000)),expiresAt=new Date(Date.now()+300000).toISOString();this.store.pairings.set(id,{id,connectorId,deviceId,code,expiresAt});return {pairingId:id,code,expiresAt};}
  claimPairing(pairingId:string,code:string,userId:string){const p=this.store.pairings.get(pairingId),c=p&&this.store.connectors.get(p.connectorId);if(!p||p.code!==code||Date.parse(p.expiresAt)<Date.now()||!c||c.userId!==userId)throw new Error('UNAUTHORIZED');p.claimed=true;return {status:'claimed',pairingId};}
  bind(userId:string,connectorId:string,deviceId:string,requestId:string){assertClientRequestId(requestId);const device=this.store.devices.get(deviceId);const connector=this.store.connectors.get(connectorId);if(!device||!connector||connector.userId!==userId)throw new Error('UNAUTHORIZED');const existing=[...this.store.bindings.values()].find(b=>b.deviceId===deviceId&&b.state==='active');if(existing)return existing;const b={id:`bind-${randomUUID()}`,userId,connectorId,deviceId,epoch:1,state:'active' as const,selectionRevision:'0',grantsVersion:'0',deviceToken:randomUUID()+randomUUID()};this.store.bindings.set(b.id,b);this.store.grants.set(b.id,new Set());return b;}
  setGrants(bindingId:string,refs:Grant[],expected:string,requestId:string){assertClientRequestId(requestId);const old=this.store.idempotent(`binding:${bindingId}`,'grants',requestId,{refs,expected});if(!('k' in old))return old;const b=this.store.getBinding(bindingId);if(b.grantsVersion!==expected)throw new Error('CATALOG_CHANGED');for(const ref of refs){const task=this.store.tasks.get(this.store.key(ref));if(ref.connectorId!==b.connectorId||!task||task.projectId!==ref.projectId)throw new Error('TARGET_UNAVAILABLE');}const set=new Set(refs.map(r=>this.store.grantKey(r)));b.grantsVersion=String(Number(b.grantsVersion)+1);this.store.grants.set(bindingId,set);const result={grantsVersion:b.grantsVersion,grants:refs};this.store.saveIdempotent(old.k,`binding:${bindingId}`,'grants',requestId,old.bodyHash,result);return result;}
  catalog(bindingId:string,kind:'projects'|'tasks',projectId?:string,limit=5,cursor=0){const b=this.store.getBinding(bindingId);const grants=this.store.grants.get(bindingId)??new Set();let values=kind==='projects'?[...this.store.projects.values()].filter(p=>p.connectorId===b.connectorId&&[...grants].some(k=>k.startsWith(`${b.connectorId}:${p.projectId}:`))):[...this.store.tasks.values()].filter(t=>t.connectorId===b.connectorId&&(!projectId||t.projectId===projectId)&&grants.has(this.store.grantKey(t)));const page=values.slice(cursor,Math.min(cursor+Math.min(limit,20),values.length));return {items:page,nextCursor:cursor+page.length<values.length?String(cursor+page.length):undefined,catalogVersion:'1'};}
  select(bindingId:string,ref:TaskRef,expected:string,requestId:string){assertClientRequestId(requestId);const old=this.store.idempotent(`binding:${bindingId}`,'selection',requestId,{ref,expected});if(!('k' in old))return old;const b=this.store.getBinding(bindingId);if(b.selectionRevision!==expected)throw new Error('SELECTION_CONFLICT');this.store.ensureGrant(b,ref);b.activeTaskRef=ref;b.selectionRevision=String(Number(b.selectionRevision)+1);const result={activeTaskRef:ref,selectionRevision:b.selectionRevision};this.store.saveIdempotent(old.k,`binding:${bindingId}`,'selection',requestId,old.bodyHash,result);return result;}
  createRecording(bindingId:string,target:TaskRef,selectionRevision:string,requestId:string,transcript=''){assertClientRequestId(requestId);const old=this.store.idempotent(`binding:${bindingId}`,'recording',requestId,{target,selectionRevision,transcript});if(!('k' in old))return old;const b=this.store.getBinding(bindingId);if(b.epoch<1||b.selectionRevision!==selectionRevision||JSON.stringify(b.activeTaskRef)!==JSON.stringify(target))throw new Error('SELECTION_CONFLICT');this.store.ensureGrant(b,target);const r={id:`rec-${randomUUID()}`,bindingId,epoch:b.epoch,target,selectionRevision,clientRequestId:requestId,status:'ready' as const,transcript};this.store.recordings.set(r.id,r);this.store.saveIdempotent(old.k,`binding:${bindingId}`,'recording',requestId,old.bodyHash,r);return r;}
  submitMessage(bindingId:string,recordingId:string,target:TaskRef,selectionRevision:string,requestId:string){assertClientRequestId(requestId);const old=this.store.idempotent(`binding:${bindingId}`,'message',requestId,{recordingId,target,selectionRevision});if(!('k' in old))return old;const b=this.store.getBinding(bindingId),r=this.store.recordings.get(recordingId);if(!r||r.status!=='ready'||!r.transcript?.trim())throw new Error('ASR_FAILED');if(r.bindingId!==bindingId||r.epoch!==b.epoch||r.selectionRevision!==selectionRevision||JSON.stringify(r.target)!==JSON.stringify(target)||JSON.stringify(b.activeTaskRef)!==JSON.stringify(target))throw new Error('TARGET_MOVED');this.store.ensureGrant(b,target);const id=`msg-${randomUUID()}`,commandId=`cmd-${randomUUID()}`;const m={id,bindingId,epoch:b.epoch,target,recordingId,clientRequestId:requestId,status:'accepted' as const,text:r.transcript??'',commandId};this.store.messages.set(id,m);const command={commandId,messageId:id,connectorId:target.connectorId,bindingId,bindingEpoch:b.epoch,grantsVersion:b.grantsVersion,target,text:m.text,state:'available' as const,expiresAt:new Date(Date.now()+600000).toISOString()};this.store.commands.set(commandId,command);this.store.saveIdempotent(old.k,`binding:${bindingId}`,'message',requestId,old.bodyHash,m);return m;}
  claimCommand(commandId:string,connectorId:string,connectionEpoch:string,requestId:string){assertClientRequestId(requestId);const c=this.store.commands.get(commandId);if(!c||c.connectorId!==connectorId)throw new Error('NOT_FOUND');const conn=this.store.connectors.get(connectorId);const b=this.store.bindings.get(c.bindingId);if(!conn||connectionEpoch!==conn.connectionEpoch||!b||b.state!=='active'||b.epoch!==c.bindingEpoch)throw new Error('BINDING_REVOKED');this.store.ensureGrant(b,c.target);if(c.executionId)return c;if(c.state!=='available'||Date.parse(c.expiresAt)<Date.now())throw new Error('BUSY');c.executionId=`exec-${randomUUID()}`;c.state='claimed';const m=this.store.messages.get(c.messageId);if(m)m.status='dispatching';return c;}
  revoke(bindingId:string,requestId:string){assertClientRequestId(requestId);const b=this.store.getBinding(bindingId);b.state='revoked';b.epoch++;for(const c of this.store.commands.values())if(c.bindingId===bindingId&&c.state==='available')c.state='cancelled';return {bindingId,epoch:b.epoch,revokedAt:nowIso()};}
}
