import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {existsSync} from 'node:fs';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdtemp,mkdir,readFile,rm,writeFile,chmod,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const run=promisify(execFile);
const repoRoot=resolve(dirname(fileURLToPath(import.meta.url)),'../../..');

test('bootstrap uses the existing Connector upgrade path and preserves config', {skip:process.platform!=='darwin'||process.arch!=='arm64'}, async t=>{
  const root=await mkdtemp(join(tmpdir(),'hc-bootstrap-existing-'));
  t.after(()=>rm(root,{recursive:true,force:true}));
  const home=join(root,'home'),installRoot=join(home,'Library','Application Support','HardwareCompanion','connector');
  const current=join(installRoot,'current'),fixture=join(root,'fixture','release'),bin=join(root,'bin');
  await mkdir(join(current,'bin'),{recursive:true}); await mkdir(join(fixture,'runtime'),{recursive:true}); await mkdir(join(fixture,'bin'),{recursive:true}); await mkdir(bin,{recursive:true});
  const config=join(home,'Library','Application Support','HardwareCompanion','config.json');
  await writeFile(config,'{"bindingId":"keep-existing-binding"}\n');
  const invocationLog=join(root,'invocations');
  const companion=join(current,'bin','companion');
  await writeFile(companion,'#!/bin/sh\nprintf "current:%s\\n" "$*" >> "$HC_TEST_INVOCATIONS"\n'); await chmod(companion,0o755);
  const candidateCompanion=join(fixture,'bin','companion');
  await writeFile(candidateCompanion,'#!/bin/sh\nprintf "candidate:%s\\n" "$*" >> "$HC_TEST_INVOCATIONS"\nif [ "${HC_TEST_UPDATE_FAIL:-0}" = 1 ]; then printf \'%s\\n\' \'{"ok":true,"operation":"update","data":{"updated":false,"rolledBack":true}}\'; else printf \'%s\\n\' \'{"ok":true,"operation":"update","data":{"updated":true,"rolledBack":false}}\'; fi\n'); await chmod(candidateCompanion,0o755);
  await writeFile(join(current,'VERSION'),'0.3.5\n');
  await writeFile(join(fixture,'VERSION'),'0.3.10\n');
  await writeFile(join(fixture,'runtime','node'),'#!/bin/sh\nexit 0\n');
  await chmod(join(fixture,'runtime','node'),0o755);
  const archive=join(root,'release.tar.gz');
  await run('tar',['-czf',archive,'-C',join(root,'fixture'),'release']);
  const hash=createHash('sha256').update(await readFile(archive)).digest('hex');
  const sidecar=join(root,'release.sha256');
  await writeFile(sidecar,`${hash}  hardware-companion-macos-arm64-v0.3.10.tar.gz\n`);
  const curl=join(bin,'curl');
  await writeFile(curl,'#!/bin/sh\nfor arg in "$@"; do case "$arg" in https://gamecncom.nat200.top/*) if [ "${HC_TEST_FAIL_OWN_SOURCE:-0}" = 1 ]; then exit 22; fi;; esac; done\nwhile [ "$#" -gt 0 ]; do if [ "$1" = "--output" ]; then shift; out="$1"; fi; shift; done\ncase "$out" in *.sha256) cp "$HC_TEST_CHECKSUM" "$out";; *) cp "$HC_TEST_ARCHIVE" "$out";; esac\n');
  await chmod(curl,0o755);
  const script=join(repoRoot,'skills','hardware-companion','scripts','bootstrap-macos-arm64.sh');
  await run('/bin/sh',[script],{env:{...process.env,HOME:home,HC_INSTALL_ROOT:installRoot,HC_BOOTSTRAP_NODE:process.execPath,HC_TEST_ARCHIVE:archive,HC_TEST_CHECKSUM:sidecar,HC_TEST_INVOCATIONS:invocationLog,PATH:`${bin}:${process.env.PATH}`}});
  const calls=(await readFile(invocationLog,'utf8')).trim().split('\n');
  assert.match(calls[0],/^candidate:update --from .*\/release --install-root /);
  assert.match(calls[1],/^current:service install --install-root /);
  assert.equal(await readFile(config,'utf8'),'{"bindingId":"keep-existing-binding"}\n');
  const fallback=await run('/bin/sh',[script],{env:{...process.env,HOME:home,HC_INSTALL_ROOT:installRoot,HC_BOOTSTRAP_NODE:process.execPath,HC_TEST_ARCHIVE:archive,HC_TEST_CHECKSUM:sidecar,HC_TEST_INVOCATIONS:invocationLog,HC_TEST_FAIL_OWN_SOURCE:'1',PATH:`${bin}:${process.env.PATH}`}});
  assert.match(fallback.stderr,/github-fallback:hardware-companion-macos-arm64/);
  await assert.rejects(()=>run('/bin/sh',[script],{env:{...process.env,HOME:home,HC_INSTALL_ROOT:installRoot,HC_BOOTSTRAP_NODE:process.execPath,HC_TEST_ARCHIVE:archive,HC_TEST_CHECKSUM:sidecar,HC_TEST_INVOCATIONS:invocationLog,HC_TEST_UPDATE_FAIL:'1',PATH:`${bin}:${process.env.PATH}`}}),/UPDATE_NOT_APPLIED/);
});

test('same version with valid checksums and runtime skips download and restart', {skip:process.platform!=='darwin'||process.arch!=='arm64'}, async t => {
  const root = await mkdtemp(join(tmpdir(),'hc-bootstrap-reuse-'));
  t.after(()=>rm(root,{recursive:true,force:true}));
  const installRoot=join(root,'installed connector'),current=join(installRoot,'current'),bin=join(root,'bin');
  await mkdir(join(current,'bin'),{recursive:true}); await mkdir(bin);
  await writeFile(join(current,'VERSION'),'0.3.10\n');
  await writeFile(join(current,'runtime-node-path'),process.execPath+'\n');
  const companion=join(current,'bin','companion');
  await writeFile(companion,'#!/bin/sh\nprintf \'%s\\n\' \'{"ok":true,"operation":"service status","data":{"loaded":true,"running":true}}\'\n');
  await chmod(companion,0o755);
  const files=['VERSION','runtime-node-path','bin/companion'];
  await writeFile(join(current,'checksums.sha256'),(await Promise.all(files.map(async file => `${createHash('sha256').update(await readFile(join(current,file))).digest('hex')}  ${file}`))).join('\n')+'\n');
  await writeFile(join(bin,'curl'),'#!/bin/sh\necho unwanted-download >&2\nexit 9\n'); await chmod(join(bin,'curl'),0o755);
  const script=join(repoRoot,'skills','hardware-companion','scripts','bootstrap-macos-arm64.sh');
  const result=await run('/bin/sh',[script],{env:{...process.env,HC_INSTALL_ROOT:installRoot,PATH:`${bin}:${process.env.PATH}`}});
  assert.match(result.stdout,/"reused":true/);
  assert.match(result.stdout,/"downloaded":false/);
  assert.doesNotMatch(result.stderr,/unwanted-download/);
});

const officialRuntimeArchive=join(repoRoot,'apps','connector','artifacts','runtime','node-v24.21.0-darwin-arm64.tar.xz');
test('no compatible Node installs the fixed private arm64 runtime into an isolated cache', {skip:process.platform!=='darwin'||process.arch!=='arm64'||!existsSync(officialRuntimeArchive)}, async t => {
  const root=await mkdtemp(join(tmpdir(),'hc-no-node-fixture-'));
  t.after(()=>rm(root,{recursive:true,force:true}));
  const installRoot=join(root,'connector install with spaces'),runtimeRoot=join(root,'runtime cache with spaces');
  const fixture=join(root,'fixture','release'),bin=join(root,'fake bin');
  await mkdir(join(fixture,'bin'),{recursive:true}); await mkdir(join(fixture,'scripts'),{recursive:true}); await mkdir(bin);
  await writeFile(join(fixture,'bin','companion'),'#!/bin/sh\nprintf \'%s\\n\' \'{"ok":true,"operation":"service install","data":{"loaded":true}}\'\n');
  await chmod(join(fixture,'bin','companion'),0o755);
  await writeFile(join(fixture,'VERSION'),'0.3.10\n');
  await writeFile(join(fixture,'scripts','install-package.mjs'),`import {promises as fs} from 'node:fs';import {join} from 'node:path';const args=process.argv;const root=args[args.indexOf('--install-root')+1];const source=args[args.indexOf('--from')+1];await fs.mkdir(join(root,'current','bin'),{recursive:true});await fs.copyFile(join(source,'bin','companion'),join(root,'current','bin','companion'));await fs.chmod(join(root,'current','bin','companion'),0o755);await fs.copyFile(join(source,'VERSION'),join(root,'current','VERSION'));await fs.copyFile(join(source,'runtime-node-path'),join(root,'current','runtime-node-path'));console.log(JSON.stringify({ok:true,operation:'install'}));`);
  const archive=join(root,'business.tar.gz');
  await run('tar',['-czf',archive,'-C',join(root,'fixture'),'release']);
  const archiveSha=createHash('sha256').update(await readFile(archive)).digest('hex');
  const businessSidecar=join(root,'business.sha256');
  await writeFile(businessSidecar,`${archiveSha}  hardware-companion-macos-arm64-v0.3.10.tar.gz\n`);
  const runtimeSidecar=join(root,'runtime.sha256');
  await writeFile(runtimeSidecar,'6239d4cf92d864487ec8cd3615038f7b67e7f58b77b21cd2f09ea9fbd68065fe  node-v24.21.0-darwin-arm64.tar.xz\n');
  const curl=join(bin,'curl');
  await writeFile(curl,'#!/bin/sh\nfor arg in "$@"; do case "$arg" in https://*) url="$arg";; esac; done\nwhile [ "$#" -gt 0 ]; do if [ "$1" = "--output" ]; then shift; out="$1"; fi; shift; done\ncase "$url" in *node-v24.21.0-darwin-arm64.tar.xz.sha256) cp "$HC_TEST_NODE_CHECKSUM" "$out";; *node-v24.21.0-darwin-arm64.tar.xz) cp "$HC_TEST_NODE_ARCHIVE" "$out";; *.sha256) cp "$HC_TEST_CHECKSUM" "$out";; *) cp "$HC_TEST_ARCHIVE" "$out";; esac\n');
  await chmod(curl,0o755);
  const script=join(repoRoot,'skills','hardware-companion','scripts','bootstrap-macos-arm64.sh');
  const result=await run('/bin/sh',[script],{env:{...process.env,HC_INSTALL_ROOT:installRoot,HC_RUNTIME_ROOT:runtimeRoot,HC_BOOTSTRAP_NODE:'/missing-in-fixture',HC_TEST_NODE_ARCHIVE:officialRuntimeArchive,HC_TEST_NODE_CHECKSUM:runtimeSidecar,HC_TEST_ARCHIVE:archive,HC_TEST_CHECKSUM:businessSidecar,PATH:`${bin}:${process.env.PATH}`}});
  assert.match(result.stdout,/"operation":"bootstrap"/);
  assert.equal((await readFile(join(installRoot,'current','VERSION'),'utf8')).trim(),'0.3.10');
  const cache=join(runtimeRoot,'node-v24.21.0-darwin-arm64');
  assert.ok((await readFile(join(cache,'LICENSE'),'utf8')).length>100);
  const probe=await run(join(cache,'bin','node'),['-p','process.arch']);
  assert.equal(probe.stdout.trim(),'arm64');
  assert.equal((await readFile(join(installRoot,'current','runtime-node-path'),'utf8')).trim(),await realpath(join(cache,'bin','node')));
});
